//
// Generated file, do not edit! Created by opp_msgtool 6.1 from DataRequest.msg.
//

#ifndef __DATAREQUEST_M_H
#define __DATAREQUEST_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// opp_msgtool version check
#define MSGC_VERSION 0x0601
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgtool: 'make clean' should help.
#endif

class DataRequest;
/**
 * Class generated from <tt>DataRequest.msg:16</tt> by opp_msgtool.
 * <pre>
 * message DataRequest
 * {
 *     string dataId;    // ID of the requested data
 *     string userId;    // ID of the user making the request
 * }
 * </pre>
 */
class DataRequest : public ::omnetpp::cMessage
{
  protected:
    omnetpp::opp_string dataId;
    omnetpp::opp_string userId;

  private:
    void copy(const DataRequest& other);

  protected:
    bool operator==(const DataRequest&) = delete;

  public:
    DataRequest(const char *name=nullptr, short kind=0);
    DataRequest(const DataRequest& other);
    virtual ~DataRequest();
    DataRequest& operator=(const DataRequest& other);
    virtual DataRequest *dup() const override {return new DataRequest(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual const char * getDataId() const;
    virtual void setDataId(const char * dataId);

    virtual const char * getUserId() const;
    virtual void setUserId(const char * userId);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const DataRequest& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, DataRequest& obj) {obj.parsimUnpack(b);}


namespace omnetpp {

template<> inline DataRequest *fromAnyPtr(any_ptr ptr) { return check_and_cast<DataRequest*>(ptr.get<cObject>()); }

}  // namespace omnetpp

#endif // ifndef __DATAREQUEST_M_H

