//
// Generated file, do not edit! Created by opp_msgtool 6.1 from ManagerMessage.msg.
//

#ifndef __MANAGERMESSAGE_M_H
#define __MANAGERMESSAGE_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// opp_msgtool version check
#define MSGC_VERSION 0x0601
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgtool: 'make clean' should help.
#endif

class ManagerMessage;
/**
 * Class generated from <tt>ManagerMessage.msg:16</tt> by opp_msgtool.
 * <pre>
 * message ManagerMessage
 * {
 *     int edgeId;
 *     string dataId;
 *     string userId;
 * }
 * </pre>
 */
class ManagerMessage : public ::omnetpp::cMessage
{
  protected:
    int edgeId = 0;
    omnetpp::opp_string dataId;
    omnetpp::opp_string userId;

  private:
    void copy(const ManagerMessage& other);

  protected:
    bool operator==(const ManagerMessage&) = delete;

  public:
    ManagerMessage(const char *name=nullptr, short kind=0);
    ManagerMessage(const ManagerMessage& other);
    virtual ~ManagerMessage();
    ManagerMessage& operator=(const ManagerMessage& other);
    virtual ManagerMessage *dup() const override {return new ManagerMessage(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual int getEdgeId() const;
    virtual void setEdgeId(int edgeId);

    virtual const char * getDataId() const;
    virtual void setDataId(const char * dataId);

    virtual const char * getUserId() const;
    virtual void setUserId(const char * userId);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const ManagerMessage& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, ManagerMessage& obj) {obj.parsimUnpack(b);}


namespace omnetpp {

template<> inline ManagerMessage *fromAnyPtr(any_ptr ptr) { return check_and_cast<ManagerMessage*>(ptr.get<cObject>()); }

}  // namespace omnetpp

#endif // ifndef __MANAGERMESSAGE_M_H

