//
// Generated file, do not edit! Created by opp_msgtool 6.1 from SendingUserData.msg.
//

#ifndef __SENDINGUSERDATA_M_H
#define __SENDINGUSERDATA_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// opp_msgtool version check
#define MSGC_VERSION 0x0601
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgtool: 'make clean' should help.
#endif

class SendingUserData;
/**
 * Class generated from <tt>SendingUserData.msg:16</tt> by opp_msgtool.
 * <pre>
 * message SendingUserData
 * {
 *     string dataId;    // ID of the requested data
 *     string userId = nullptr;    // ID of the user making the request
 * }
 * </pre>
 */
class SendingUserData : public ::omnetpp::cMessage
{
  protected:
    omnetpp::opp_string dataId;
    omnetpp::opp_string userId = nullptr;

  private:
    void copy(const SendingUserData& other);

  protected:
    bool operator==(const SendingUserData&) = delete;

  public:
    SendingUserData(const char *name=nullptr, short kind=0);
    SendingUserData(const SendingUserData& other);
    virtual ~SendingUserData();
    SendingUserData& operator=(const SendingUserData& other);
    virtual SendingUserData *dup() const override {return new SendingUserData(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual const char * getDataId() const;
    virtual void setDataId(const char * dataId);

    virtual const char * getUserId() const;
    virtual void setUserId(const char * userId);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const SendingUserData& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, SendingUserData& obj) {obj.parsimUnpack(b);}


namespace omnetpp {

template<> inline SendingUserData *fromAnyPtr(any_ptr ptr) { return check_and_cast<SendingUserData*>(ptr.get<cObject>()); }

}  // namespace omnetpp

#endif // ifndef __SENDINGUSERDATA_M_H

